java_library(
    name = "commons-httpclient",
    exports = [
        "//external:jar/commons-httpclient/commons-httpclient"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


