java_library(
    name = "metrics-core",
    exports = [
        "//external:jar/com/yammer/metrics/metrics-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


