java_library(
    name = "AppleJavaExtensions",
    exports = [
        "//external:jar/com/apple/AppleJavaExtensions"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


