java_library(
    name = "curvesapi",
    exports = [
        "//external:jar/com/github/virtuald/curvesapi"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


