java_library(
    name = "xalan",
    exports = [
        "//external:jar/xalan/xalan"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/xml-apis:xml-apis"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


