java_library(
    name = "thrift-server",
    exports = [
        "//external:jar/com/thinkaurelius/thrift/thrift-server"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/lmax:disruptor",
        "//dependencies/maven/artifacts/junit:junit",
        "//dependencies/maven/artifacts/org/apache/thrift:libthrift"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


