java_library(
    name = "ejml",
    exports = [
        "//external:jar/com/googlecode/efficient-java-matrix-library/ejml"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


