java_library(
    name = "metrics-ganglia",
    exports = [
        "//external:jar/com/codahale/metrics/metrics-ganglia"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/info/ganglia/gmetric4j:gmetric4j"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "metrics-graphite",
    exports = [
        "//external:jar/com/codahale/metrics/metrics-graphite"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


