java_library(
    name = "xom",
    exports = [
        "//external:jar/com/io7m/xom/xom"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/xalan:xalan",
        "//dependencies/maven/artifacts/xerces:xercesImpl",
        "//dependencies/maven/artifacts/xml-apis:xml-apis"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


