java_library(
    name = "libthrift",
    exports = [
        "//external:jar/org/apache/thrift/libthrift"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpclient",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpcore"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


