java_library(
    name = "javax-activation-api",
    exports = [
        "//external:jar/javax/activation/javax-activation-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


