java_library(
    name = "jaxb-core",
    exports = [
        "//external:jar/com/sun/xml/bind/jaxb-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "jaxb-impl",
    exports = [
        "//external:jar/com/sun/xml/bind/jaxb-impl"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


