java_library(
    name = "jollyday",
    exports = [
        "//external:jar/de/jollyday/jollyday"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/javax/xml/bind:jaxb-api",
        "//dependencies/maven/artifacts/joda-time:joda-time"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


