java_library(
    name = "jets3t",
    exports = [
        "//external:jar/net/java/dev/jets3t/jets3t"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/jamesmurty/utils:java-xmlbuilder",
        "//dependencies/maven/artifacts/javax/mail:mail",
        "//dependencies/maven/artifacts/mx4j:mx4j",
        "//dependencies/maven/artifacts/org/bouncycastle:bcprov-jdk15on"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


