java_library(
    name = "logback-classic",
    exports = [
        "//external:jar/ch/qos/logback/logback-classic"
    ],
    runtime_deps = [
        ":logback-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "logback-core",
    exports = [
        "//external:jar/ch/qos/logback/logback-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


