java_library(
    name = "commons-lang",
    exports = [
        "//external:jar/commons-lang/commons-lang"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


