java_library(
    name = "utils",
    srcs = glob(["*.java"]),
    deps = [
        "@graknlabs_client_java//:client-java",
        "@graknlabs_graql//java:graql",
    ],
    visibility = [
        "//visibility:public"
    ]
)
