define


clinical-trial-relevant-therapeutic-gene-variant-disease sub rule
when {
    $p isa person has age $a, has gender $gen;
    $g isa gene has gene-symbol $gs;
    $v isa variant has variant-symbol $vs;
    $d isa disease;
    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender $pgen, has title $t;
    (genome-owner: $p, identified-gene: $g) isa gene-identification;
    (genome-owner: $p, identified-variant: $v) isa variant-identification;
    (patient: $p, diagnosed-disease: $d) isa diagnosis;
    (treatment-method: $ct, treatment-subject: $d) isa experimental-treatment;
    $a >= $min;
    $a <= $max;
    $gen == $pgen;
    $t contains $gs;
    $t contains $vs;
}
then {
    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy;
};

clinical-trial-relevant-therapeutic-gene-variant-disease-All sub rule
when {
    $p isa person has age $a, has gender $gen;
    $g isa gene has gene-symbol $gs;
    $v isa variant has variant-symbol $vs;
    $d isa disease;
    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender "All", has title $t;
    (genome-owner: $p, identified-gene: $g) isa gene-identification;
    (genome-owner: $p, identified-variant: $v) isa variant-identification;
    (patient: $p, diagnosed-disease: $d) isa diagnosis;
    (treatment-method: $ct, treatment-subject: $d) isa experimental-treatment;
    $a >= $min;
    $a <= $max;
    $t contains $gs;
    $t contains $vs;
}
then {
    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy;
};

#clinical-trial-relevant-therapeutic-gene sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $g isa gene has gene-symbol $gs;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender $pgen, has title $t;
#    (genome-owner: $p, identified-gene: $g) isa gene-identification;
#    $a >= $min;
#    $a <= $max;
#    $gen == $pgen;
#    $t contains $gs;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-1;
#};
#
#clinical-trial-relevant-therapeutic-gene-All sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $g isa gene has gene-symbol $gs;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender "All", has title $t;
#    (genome-owner: $p, identified-gene: $g) isa gene-identification;
#    $a >= $min;
#    $a <= $max;
#    $t contains $gs;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-1;
#};
#
#########
#
#clinical-trial-relevant-therapeutic-variant sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $v isa variant has variant-symbol $vs;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender $pgen, has title $t;
#    (genome-owner: $p, identified-variant: $v) isa variant-identification;
#    $a >= $min;
#    $a <= $max;
#    $gen == $pgen;
#    $t contains $vs;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-1;
#};
#
#clinical-trial-relevant-therapeutic-variant-All sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $v isa variant has variant-symbol $vs;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender "All", has title $t;
#    (genome-owner: $p, identified-variant: $v) isa variant-identification;
#    $a >= $min;
#    $a <= $max;
#    $t contains $vs;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-1;
#};
#
#########
#
#clinical-trial-relevant-therapeutic-disease sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $d isa disease;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender $pgen, has title $t;
#    (patient: $p, diagnosed-disease: $d) isa diagnosis;
#    (treatment-method: $ct, treatment-subject: $d) isa experimental-treatment;
#    $a >= $min;
#    $a <= $max;
#    $gen == $pgen;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-1;
#};
#
#clinical-trial-relevant-therapeutic-disease-All sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $d isa disease;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender "All", has title $t;
#    (patient: $p, diagnosed-disease: $d) isa diagnosis;
#    (treatment-method: $ct, treatment-subject: $d) isa experimental-treatment;
#    $a >= $min;
#    $a <= $max;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-1;
#};
#
#########
#
#clinical-trial-relevant-therapeutic-gene-variant sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $g isa gene has gene-symbol $gs;
#    $v isa variant has variant-symbol $vs;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender $pgen, has title $t;
#    (genome-owner: $p, identified-gene: $g) isa gene-identification;
#    (genome-owner: $p, identified-variant: $v) isa variant-identification;
#    $a >= $min;
#    $a <= $max;
#    $gen == $pgen;
#    $t contains $gs;
#    $t contains $vs;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-2;
#};
#
#clinical-trial-relevant-therapeutic-gene-variant-All sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $g isa gene has gene-symbol $gs;
#    $v isa variant has variant-symbol $vs;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender "All", has title $t;
#    (genome-owner: $p, identified-gene: $g) isa gene-identification;
#    (genome-owner: $p, identified-variant: $v) isa variant-identification;
#    $a >= $min;
#    $a <= $max;
#    $t contains $gs;
#    $t contains $vs;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-2;
#};
#
#########
#
#clinical-trial-relevant-therapeutic-gene-disease sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $g isa gene has gene-symbol $gs;
#    $d isa disease;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender $pgen, has title $t;
#    (genome-owner: $p, identified-gene: $g) isa gene-identification;
#    (patient: $p, diagnosed-disease: $d) isa diagnosis;
#    (treatment-method: $ct, treatment-subject: $d) isa experimental-treatment;
#    $a >= $min;
#    $a <= $max;
#    $gen == $pgen;
#    $t contains $gs;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-2;
#};
#
#clinical-trial-relevant-therapeutic-gene-disease-All sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $g isa gene has gene-symbol $gs;
#    $d isa disease;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender "All", has title $t;
#    (genome-owner: $p, identified-gene: $g) isa gene-identification;
#    (patient: $p, diagnosed-disease: $d) isa diagnosis;
#    (treatment-method: $ct, treatment-subject: $d) isa experimental-treatment;
#    $a >= $min;
#    $a <= $max;
#    $t contains $gs;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-2;
#};
#
#########
#
#clinical-trial-relevant-therapeutic-variant-disease sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $v isa variant has variant-symbol $vs;
#    $d isa disease;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender $pgen, has title $t;
#    (genome-owner: $p, identified-variant: $v) isa variant-identification;
#    (patient: $p, diagnosed-disease: $d) isa diagnosis;
#    (treatment-method: $ct, treatment-subject: $d) isa experimental-treatment;
#    $a >= $min;
#    $a <= $max;
#    $gen == $pgen;
#    $t contains $vs;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-2;
#};
#
#clinical-trial-relevant-therapeutic-variant-disease-All sub rule
#when {
#    $p isa person has age $a, has gender $gen;
#    $v isa variant has variant-symbol $vs;
#    $d isa disease;
#    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender "All", has title $t;
#    (genome-owner: $p, identified-variant: $v) isa variant-identification;
#    (patient: $p, diagnosed-disease: $d) isa diagnosis;
#    (treatment-method: $ct, treatment-subject: $d) isa experimental-treatment;
#    $a >= $min;
#    $a <= $max;
#    $t contains $vs;
#}
#then {
#    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy-level-2;
#};
#
#########
