define

drug-relevant-therapeutic-variant-disease sub rule,
    when {
        $p isa person;
        $di isa disease;
        $dr isa drug;
        $v isa variant;
        (genome-owner: $p, identified-variant: $v) isa variant-identification;
        (patient: $p, diagnosed-disease: $di) isa diagnosis;
        (associated-disease: $di, associated-drug: $dr) isa drug-disease-association;
        (associated-variant: $v, associated-drug: $dr) isa drug-variant-association;
    },
    then {
        (patient: $p, relevant-therapeutic: $dr) isa personalised-therapy;
    };



#drug-relevant-therapeutic-variant sub rule,
#    when {
#      $p isa person;
#      $dr isa drug;
#      $v isa variant;
#      (genome-owner: $p, identified-variant: $v) isa variant-identification;
#      (associated-variant: $v, associated-drug: $dr) isa drug-variant-association;
#    },
#    then {
#      (patient: $p, relevant-therapeutic: $dr) isa personalised-therapy-level-1;
#    };
#
#drug-relevant-therapeutic-disease sub rule,
#    when {
#        $p isa person;
#        $di isa disease;
#        $dr isa drug;
#        (patient: $p, diagnosed-disease: $di) isa diagnosis;
#        (associated-disease: $di, associated-drug: $dr) isa drug-disease-association;
#    },
#    then {
#        (patient: $p, relevant-therapeutic: $dr) isa personalised-therapy-level-1;
#    };
#
