define

person-id sub attribute datatype double;
age sub attribute datatype double;
gender sub attribute datatype string;
disease-id sub attribute datatype string;
source sub attribute datatype string;
gene-id sub attribute datatype string;
snp-id sub attribute datatype string;
pm-id sub attribute datatype double;
abstract sub attribute datatype string;
score sub attribute datatype double;
url sub attribute datatype string;
min-age sub attribute datatype double;
max-age sub attribute datatype double;
variant-symbol sub attribute datatype string;
gene-symbol sub attribute datatype string;
nct-id sub attribute datatype string;
status sub attribute datatype string;
results sub attribute datatype boolean;
intervention-type sub attribute datatype string;
mesh-id sub attribute datatype string;
drug-bank-id sub attribute datatype string;
pub-chem-cid sub attribute datatype string;
participants-gender sub attribute datatype string;
title sub attribute datatype string;

name sub attribute datatype string;
disease-name sub name;
drug-name sub name;



person sub entity,
    has person-id,
    has age,
    has gender,
    plays patient,
    plays genome-owner;

disease sub entity,
    has disease-name,
    has disease-id,
    has source,
    plays diagnosed-disease,
    plays associated-disease,
    plays treatment-subject,
    plays mentioned-disease;

gene sub entity,
    has gene-id,
    has gene-symbol,
    plays varied-gene,
    plays identified-gene,
    plays mentioned-gene;

variant sub entity,
    has variant-symbol,
    has snp-id,
    plays mentioned-variant,
    plays identified-variant,
    plays genetic-variant;

pubmed-article sub entity,
    has pm-id,
    has title,
    has abstract,
    plays mined-pubmed-article
    plays relevant-therapeutic;

drug sub entity,
    has drug-name,
    has mesh-id,
    has drug-bank-id,
    has pub-chem-cid,
    plays associated-drug
    plays relevant-therapeutic
    plays used;

clinical-trial sub entity,
    has nct-id,
    has status,
    has results,
    has intervention-type,
    has url,
    has title,
    has min-age,
    has max-age,
    has participants-gender,
    plays relevant-therapeutic,
    plays treatment-method
    plays user;

experimental-treatment sub relationship,
    relates treatment-subject,
    relates treatment-method;

diagnosis sub relationship,
    relates patient,
    relates diagnosed-disease;

gene-identification sub relationship,
    relates identified-gene,
    relates genome-owner;

variant-identification sub relationship,
    relates identified-variant,
    relates genome-owner;

genetic-variation sub relationship,
    relates genetic-variant,
    relates varied-gene;

text-mined-analysis sub relationship,
    has score,
    relates mined-pubmed-article,
    relates mentioned-disease,
    relates mentioned-gene,
    relates mentioned-variant;

drug-disease-association sub relationship,
    relates associated-disease,
    relates associated-drug;

personalised-therapy sub relationship,
    relates patient,
    relates relevant-therapeutic;

append-relevant-therapeutic-drug sub rule,
when {
    $p isa person;
    $di isa disease;
    $dr isa drug;
    (patient: $p, diagnosed-disease: $di) isa diagnosis;
    (associated-disease: $di, associated-drug: $dr) isa drug-disease-association;
},
then {
    (patient: $p, relevant-therapeutic: $dr) isa personalised-therapy;
};

append-relevant-therapeutic-clinical-trial sub rule
when {
    $p isa person has age $a, has gender $gen;
    $g isa gene has gene-symbol $gs;
    $di isa disease;
    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender $pgen, has title $t;
    (genome-owner: $p, identified-gene: $g) isa gene-identification;
    (patient: $p, diagnosed-disease: $di) isa diagnosis;
    (treatment-method: $ct, treatment-subject: $di) isa experimental-treatment;
    $a >= $min;
    $a <= $max;
    $gen == $pgen;
    $t contains $gs;
}
then {
    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy;
};

append-relevant-therapeutic-clinical-trial-all-genders sub rule
when {
    $p isa person has age $a, has gender $gen;
    $di isa disease;
    $g isa gene has gene-symbol $gs;
    $ct isa clinical-trial has min-age $min, has max-age $max, has participants-gender "All", has title $t;
    (patient: $p, diagnosed-disease: $di) isa diagnosis;
    (genome-owner: $p, identified-gene: $g) isa gene-identification;
    (treatment-method: $ct, treatment-subject: $di) isa experimental-treatment;
    $a >= $min;
    $a <= $max;
    $t contains $gs;
}
then {
    (patient: $p, relevant-therapeutic: $ct) isa personalised-therapy;
};

use sub relationship,
    relates user,
    relates used;

test sub rule
when {
    $d isa drug has drug-name $dn;
    $c isa clinical-trial has intervention-type $i;
    $i contains $dn;
}
then {
    (user: $c, used: $d) isa use;
};
