define

pubmed-relevant-therapeutic-gene-variant-disease sub rule
when {
    $p isa person;
    $g isa gene;
    $v isa variant;
    $d isa disease;
    $pa isa pubmed-article;
    (genome-owner: $p, identified-gene: $g) isa gene-identification;
    (genome-owner: $p, identified-variant: $v) isa variant-identification;
    (patient: $p, diagnosed-disease: $d) isa diagnosis;
    (mentioned-gene: $g, mentioning-pubmed-article: $pa) isa text-mined-analysis;
    (mentioned-variant: $v, mentioning-pubmed-article: $pa) isa text-mined-analysis;
    (mentioned-disease: $d, mentioning-pubmed-article: $pa) isa text-mined-analysis;
}
then {
    (patient: $p, relevant-therapeutic: $pa) isa personalised-therapy;
};

#pubmed-relevant-therapeutic-gene sub rule
#when {
#    $p isa person;
#    $g isa gene;
#    $pa isa pubmed-article;
#    (genome-owner: $p, identified-gene: $g) isa gene-identification;
#    (mentioned-gene: $g, mentioning-pubmed-article: $pa) isa text-mined-analysis;
#}
#then {
#    (patient: $p, relevant-therapeutic: $pa) isa personalised-therapy-level-1;
#};
#
#pubmed-relevant-therapeutic-variant sub rule
#when {
#    $p isa person;
#    $v isa variant;
#    $pa isa pubmed-article;
#    (genome-owner: $p, identified-variant: $v) isa variant-identification;
#    (mentioned-variant: $v, mentioning-pubmed-article: $pa) isa text-mined-analysis;
#}
#then {
#    (patient: $p, relevant-therapeutic: $pa) isa personalised-therapy-level-1;
#};
#
#pubmed-relevant-therapeutic-disease sub rule
#when {
#    $p isa person;
#    $d isa disease;
#    $pa isa pubmed-article;
#    (patient: $p, diagnosed-disease: $d) isa diagnosis;
#    (mentioned-disease: $d, mentioning-pubmed-article: $pa) isa text-mined-analysis;
#}
#then {
#    (patient: $p, relevant-therapeutic: $pa) isa personalised-therapy-level-1;
#};

#
#pubmed-relevant-therapeutic-gene-variant sub rule
#when {
#    $p isa person;
#    $g isa gene;
#    $v isa variant;
#    $pa isa pubmed-article;
#    (genome-owner: $p, identified-gene: $g) isa gene-identification;
#    (genome-owner: $p, identified-variant: $v) isa variant-identification;
#    (mentioned-gene: $g, mentioning-pubmed-article: $pa) isa text-mined-analysis;
#    (mentioned-variant: $v, mentioning-pubmed-article: $pa) isa text-mined-analysis;
#}
#then {
#    (patient: $p, relevant-therapeutic: $pa) isa personalised-therapy-level-2;
#};
#
#pubmed-relevant-therapeutic-gene-disease sub rule
#when {
#    $p isa person;
#    $g isa gene;
#    $d isa disease;
#    $pa isa pubmed-article;
#    (genome-owner: $p, identified-gene: $g) isa gene-identification;
#    (patient: $p, diagnosed-disease: $d) isa diagnosis;
#    (mentioned-gene: $g, mentioning-pubmed-article: $pa) isa text-mined-analysis;
#    (mentioned-disease: $d, mentioning-pubmed-article: $pa) isa text-mined-analysis;
#}
#then {
#    (patient: $p, relevant-therapeutic: $pa) isa personalised-therapy-level-2;
#};
#
#pubmed-relevant-therapeutic-variant-disease sub rule
#when {
#    $p isa person;
#    $v isa variant;
#    $d isa disease;
#    $pa isa pubmed-article;
#    (genome-owner: $p, identified-variant: $v) isa variant-identification;
#    (patient: $p, diagnosed-disease: $d) isa diagnosis;
#    (mentioned-variant: $v, mentioning-pubmed-article: $pa) isa text-mined-analysis;
#    (mentioned-disease: $d, mentioning-pubmed-article: $pa) isa text-mined-analysis;
#}
#then {
#    (patient: $p, relevant-therapeutic: $pa) isa personalised-therapy-level-2;
#};

