java_library(
    name = "xmlbeans",
    exports = [
        "//external:jar/org/apache/xmlbeans/xmlbeans"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


