java_library(
    name = "mjson",
    exports = [
        "//external:jar/org/sharegov/mjson"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/junit:junit"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


