java_library(
    name = "reporter-config",
    exports = [
        "//external:jar/com/addthis/metrics/reporter-config"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/yammer/metrics:metrics-core",
        "//dependencies/maven/artifacts/org/hibernate:hibernate-validator",
        "//dependencies/maven/artifacts/org/yaml:snakeyaml"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


