java_library(
    name = "jaxb-api",
    exports = [
        "//external:jar/javax/xml/bind/jaxb-api"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/javax/activation:javax-activation-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


