java_library(
    name = "stanford-corenlp",
    exports = [
        "//external:jar/edu/stanford/nlp/stanford-corenlp"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/apple:AppleJavaExtensions",
        "//dependencies/maven/artifacts/com/googlecode/efficient-java-matrix-library:ejml",
        "//dependencies/maven/artifacts/com/io7m/xom:xom",
        "//dependencies/maven/artifacts/com/sun/xml/bind:jaxb-core",
        "//dependencies/maven/artifacts/com/sun/xml/bind:jaxb-impl",
        "//dependencies/maven/artifacts/de/jollyday:jollyday",
        "//dependencies/maven/artifacts/javax/activation:javax-activation-api",
        "//dependencies/maven/artifacts/javax/servlet:javax-servlet-api",
        "//dependencies/maven/artifacts/javax/xml/bind:jaxb-api",
        "//dependencies/maven/artifacts/joda-time:joda-time",
        "//dependencies/maven/artifacts/org/apache/commons:commons-lang3",
        "//dependencies/maven/artifacts/org/apache/lucene:lucene-analyzers-common",
        "//dependencies/maven/artifacts/org/apache/lucene:lucene-core",
        "//dependencies/maven/artifacts/org/apache/lucene:lucene-queries",
        "//dependencies/maven/artifacts/org/apache/lucene:lucene-queryparser",
        "//dependencies/maven/artifacts/org/glassfish:javax-json",
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "stanford-corenlp-java-models",
    exports = [
        "//external:jar/edu/stanford/nlp/stanford-corenlp-java-models"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/apple:AppleJavaExtensions",
        "//dependencies/maven/artifacts/com/googlecode/efficient-java-matrix-library:ejml",
        "//dependencies/maven/artifacts/com/io7m/xom:xom",
        "//dependencies/maven/artifacts/com/sun/xml/bind:jaxb-core",
        "//dependencies/maven/artifacts/com/sun/xml/bind:jaxb-impl",
        "//dependencies/maven/artifacts/de/jollyday:jollyday",
        "//dependencies/maven/artifacts/javax/activation:javax-activation-api",
        "//dependencies/maven/artifacts/javax/servlet:javax-servlet-api",
        "//dependencies/maven/artifacts/javax/xml/bind:jaxb-api",
        "//dependencies/maven/artifacts/joda-time:joda-time",
        "//dependencies/maven/artifacts/org/apache/commons:commons-lang3",
        "//dependencies/maven/artifacts/org/apache/lucene:lucene-analyzers-common",
        "//dependencies/maven/artifacts/org/apache/lucene:lucene-core",
        "//dependencies/maven/artifacts/org/apache/lucene:lucene-queries",
        "//dependencies/maven/artifacts/org/apache/lucene:lucene-queryparser",
        "//dependencies/maven/artifacts/org/glassfish:javax-json",
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


